### PR TITLE
Fixes to uploads

### LINKED ISSUE #4175: Uploads bug fixes
- [x] Single file uploads not working
 - [x] Handle changes to folder during upload
 - [x] Correctly estimate time remaining
 - [x] Remove pause from folder uploads
 - [x] Handle stop of folder upload correctly
 - [x] Multiple single-file uploads not working
 - [x] Drag and dropping files always register as folder-upload

### PR DESCRIPTION
**Pull request by xiroV**
fixes #4175

### CODE REVIEW

File: frontend-web/webclient/app/Files/HTML5FileSelector.ts [hunk 1]
```diff
@@ -192,24 +195,31 @@ export function filesFromDropOrSelectEvent(event): DropEvent[] {
...
+                    while (result.length < 5000) {
+                        const batch = await traverser.fetchFiles()
+                        if (batch === null) {
+                            if (result.length === 0) {
+                                return null;
+                            } else {
+                                break;
+                            }
                         }
+                        result = [...result, ...batch];
```
Comment (Tiggles) [inline frontend-web/webclient/app/Files/HTML5FileSelector.ts:213]:
```suggestion
                        result.push(...batch);
```

File: frontend-web/webclient/app/Files/Uploader.tsx [hunk 2]
```diff
@@ -338,34 +339,40 @@ function createResumeableFolder(
...
-                const message = concatArrayBuffers(meta, new ArrayBuffer(0));
-                sent[theFile.fullPath] = 0;
-                await sendWsChunk(uploadSocket, message)
-            } else {
-                while (!reader.isEof() && !upload.terminationRequested) {
-                    const [message, chunkSize] = await constructUploadChunk(reader, fileId);
-                    await sendWsChunk(uploadSocket, message);
-                    sent[theFile.fullPath] = (sent[theFile.fullPath] ?? 0) + chunkSize;
+            try {
+                awaiting[theFile.fullPath] = 0;
```
Comment (Tiggles) [inline frontend-web/webclient/app/Files/Uploader.tsx:343]: What does the `0` signify here?

**Review by DanThrane — APPROVED** [review]
