### PR TITLE
Syncthing fixes

### LINKED ISSUE #3278: [sync] Requests to Syncthing are slow
Currently on dev requests where a write to Syncthing is required, the request takes at least 6 seconds.

### PR DESCRIPTION
**Pull request by xiroV**
### Implementation of new  Syncthing calls (fixes #3278)
Currently we are using a single main-call for (almost) all communication with Syncthing (`writeConfig`) which will fetch all devices and folders, generate a Syncthing config which will then be sent to Syncthing. However, requesting Syncthing to overwrite its config appears to make it restart (including the API server). Because of this we experience a lot of communication problems between the kTor client and Syncthing.

This PR includes implementations for less drastic calls to Syncthing, meaning that we will instead only use `writeConfig` when the service (provider) is started. Instead it will be left to Syncthing to generate/update its configuration internally using the following calls: `addFolders`, `addDevices`, `removeFolders`, `removeDevices`.

`addFolders` and `addDevices` will still fetch all folders and devices respectively, and send these to Syncthing. This is to minimize the risk of the provider and Syncthing going too much out of sync.

`removeFolders` and `removeDevices` will **only remove the requested folders and devices** respectively. An improvement to this would be to first fetch the list of folders and devices from the provider, then from Syncthing, and finally ask Syncthing to remove the difference. This is not currently implemented.

### Propagate errors properly back to orchestrator
Fixes the issue with orchestrator and provider going out of sync by properly propagating errors back to the orchestrator.

### Only rescan syncthing on startup
Currently we ask Syncthing to rescan when the service is started. We keep repeating the request (in intervals) until we get a response. However, Syncthing will only respond once it's done rescanning (which can take long). Thus, we currently keep asking Syncthing to rescan.

This PR removes any retrying of the rescan request, thus we only ask Syncthing to rescan once when the service is started, and we ignore any bad responses. In the best case Syncthing will get the request, and rescan, and otherwise it will do the rescan automatically at a later point (when the automatic rescan sets in).

Syncthing by itself does not block other requests while rescanning, but currently no requests seem to reach Syncthing. Thus, there's a chance we are blocking requests to Syncthing from the provider due to locks being occupied by the rescanning. 

This bug have only just appeared because of the high number of files added to sync.

### CODE REVIEW

**Comment by xiroV** [comment]
Latest commit should also fix the issue with orchestrator and provider going out of sync by properly propagating errors back to the orchestrator.

File: backend/file-ucloud-service/src/jvmMain/kotlin/services/SyncthingClient.kt [hunk 1]
```diff
@@ -443,28 +443,316 @@ class SyncthingClient(
...
+                                {
+                                    setParameter("devices", pendingDevices.map { it.id })
+                                },
+                                """
+                                       select f.id, f.path, f.sync_type, f.device_id as local_device_id, d.device_id, d.user_id, f.user_id
+                                       from
+                                          file_ucloud.sync_folders f join
+                                          file_ucloud.sync_devices d on f.user_id = d.user_id
+                                       where
+                                          f.device_id in (select unnest(:devices::text[]))
```
Comment (DanThrane) [inline backend/file-ucloud-service/src/jvmMain/kotlin/services/SyncthingClient.kt:488]: Could be improved with `f.device_id = some(:devices::text[])`

File: backend/file-ucloud-service/src/jvmMain/kotlin/services/SyncthingClient.kt [hunk 2]
```diff
@@ -443,28 +443,316 @@ class SyncthingClient(
...
+                                                    it.getField(SyncFoldersTable.id) == row.getField(
+                                                    SyncFoldersTable.id
+                                                ) &&
+                                                    it.getField(SyncDevicesTable.user) == row.getField(
+                                                    SyncFoldersTable.user
+                                                )
+                                            }.map {
+                                                SyncthingFolderDevice(it.getField(SyncDevicesTable.device))
+                                            },
+                                        path = File(
```
Comment (DanThrane) [inline backend/file-ucloud-service/src/jvmMain/kotlin/services/SyncthingClient.kt:515]: I would avoid using `File` for this.

File: backend/file-ucloud-service/src/jvmMain/kotlin/services/SyncthingClient.kt [hunk 3]
```diff
@@ -443,28 +443,316 @@ class SyncthingClient(
...
+                                        defaultMapper.encodeToString(newFolders),
+                                        ContentType.Application.Json
+                                    )
                                     headers {
                                         append("X-API-Key", device.apiKey)
                                     }
                                 }
 
-                                if (resp.status == HttpStatusCode.OK) {
+                                if (resp.status != HttpStatusCode.OK) {
```
Comment (DanThrane) [inline backend/file-ucloud-service/src/jvmMain/kotlin/services/SyncthingClient.kt:535]: Technically speaking this could reject requests which were successful but didn't return explicitly 200 (e.g. anything between 201-299). Seems unlikely though.

File: backend/file-ucloud-service/src/jvmMain/kotlin/services/SyncthingClient.kt [hunk 4]
```diff
@@ -443,28 +443,316 @@ class SyncthingClient(
...
+                            } catch (ex: RPCException) {
+                                throw RPCException("Invalid Syncthing Configuration", dk.sdu.cloud.calls.HttpStatusCode.BadRequest)
+                            } catch (ex: Throwable) {
+                                // Do nothing
+                            }
+                        }
+                    }
+                    lastWrite.set(Time.now())
+
+                    if (Time.now() > timeout) {
```
Comment (DanThrane) [inline backend/file-ucloud-service/src/jvmMain/kotlin/services/SyncthingClient.kt:553]: I am not entirely sure what the timeout does. As far as I can tell, we wait for the request to finish regardless. So throwing at this point, when it has finally completed, seems wasteful.

File: backend/file-ucloud-service/src/jvmMain/kotlin/services/SyncthingClient.kt [hunk 5]
```diff
@@ -443,28 +443,316 @@ class SyncthingClient(
...
+                        throw RPCException(
+                            "Unable to contact one or more syncthing clients",
+                            dk.sdu.cloud.calls.HttpStatusCode.ServiceUnavailable
+                        )
+                    }
+                }
+            }
+            lock.release()
```
Comment (DanThrane) [inline backend/file-ucloud-service/src/jvmMain/kotlin/services/SyncthingClient.kt:561]: Lock is never released if an exception is thrown above.

File: backend/file-ucloud-service/src/jvmMain/kotlin/services/SyncthingClient.kt [hunk 6]
```diff
@@ -443,28 +443,316 @@ class SyncthingClient(
...
+                mutex.withLock {
+                    deviceFolders.value.forEach { folder ->
+                        try {
+                            val resp = httpClient.delete<HttpResponse>(deviceEndpoint(deviceFolders.key, "/rest/config/folders/$folder")) {
+                                headers {
+                                    append("X-API-Key", deviceFolders.key.apiKey)
+                                }
+                            }
+
+                            if (resp.status != HttpStatusCode.OK) {
```
Comment (DanThrane) [inline backend/file-ucloud-service/src/jvmMain/kotlin/services/SyncthingClient.kt:579]: `resp.status.isSuccess()`

File: backend/file-ucloud-service/src/jvmMain/kotlin/services/SyncthingClient.kt [hunk 7]
```diff
@@ -443,28 +443,316 @@ class SyncthingClient(
...
-                            // do nothing
+                            log.error("Syncthing responded: ${ex.message}")
+                            throw RPCException(
+                                "Invalid Syncthing Configuration",
+                                dk.sdu.cloud.calls.HttpStatusCode.BadRequest
+                            )
+                        }
+                    }
+                }
+                lock.release()
```
Comment (DanThrane) [inline backend/file-ucloud-service/src/jvmMain/kotlin/services/SyncthingClient.kt:594]: Lock is never released if an exception is thrown.

File: backend/file-ucloud-service/src/jvmMain/kotlin/services/SyncthingClient.kt [hunk 8]
```diff
@@ -443,28 +443,316 @@ class SyncthingClient(
...
+
+                    if (Time.now() > timeout) {
+                        throw RPCException(
+                            "Unable to contact one or more syncthing clients",
+                            dk.sdu.cloud.calls.HttpStatusCode.ServiceUnavailable
+                        )
+                    }
+                }
+            }
+            lock.release()
```
Comment (DanThrane) [inline backend/file-ucloud-service/src/jvmMain/kotlin/services/SyncthingClient.kt:677]: Lock is not guaranteed to be released.

**Review by DanThrane — CHANGES_REQUESTED** [review]
I think there are a few things that should be changed. I would also like to have a few comments in the source code about how the timeouts are supposed to work, since we seem to always be waiting for a response from syncthing, regardless of what the timeout value is equal to.

**Review by DanThrane — APPROVED** [review]
