### PR TITLE
Minor UI fixes

### LINKED ISSUE #4185: Minor ui fixes

### PR DESCRIPTION
**Pull request by xiroV**
fixes #4185 

 - Changed color of context-switcher favorite icons for consistency
 - Reduced size of icons on shares pages for consistency
 - Prevent submit on creation of public link if field is empty
 - Corrected "empty icon" for SSH keys to be correct color, and to use hero icon.
 - Notifications for jobs now includes the name of the job (if any), not just the name of the application.

### CODE REVIEW

File: frontend-web/webclient/app/Files/SharesOutgoing.tsx [hunk 1]
```diff
@@ -510,6 +512,9 @@ export function OutgoingSharesBrowse({opts}: {opts?: ResourceBrowserOpts<Outgoin
                             height: 32,
                             width: 32,
                         }).then(setStateIcon);
+
+                        stateIcon.style.width = "24px";
+                        stateIcon.style.height = "24px";
```
Comment (Tiggles) [inline frontend-web/webclient/app/Files/SharesOutgoing.tsx:517]: Duplicated from further up

File: frontend-web/webclient/app/Notifications/index.tsx [hunk 2]
```diff
@@ -61,11 +61,17 @@ function resolveNotification(event: Notification): {
...
+            
+            if (event.meta.jobIds.length > 1) {
+                jobsCompletedTitle = `${event.meta.jobIds.length} jobs completed`;
+            } else {
+                if (event.meta.jobNames[0]) {
+                    jobsCompletedTitle = `${event.meta.jobNames[0]} completed`;
+                } else {
+                    jobsCompletedTitle = `${event.meta.appTitles[0]} completed`;
+                }
+            }
```
Comment (Tiggles) [inline frontend-web/webclient/app/Notifications/index.tsx:74]: This could factored out into a function.
`const jobsCompletedTitle = extractNotificationText(event.meta, "completed");`

**Review by DanThrane — APPROVED** [review]
