### PR TITLE
Refreshing of app overview + Removed caching of favourites

### LINKED ISSUE #2181: [scheduling] Refresh button in "Apps" does nothing

### LINKED ISSUE #2185: [scheduling] App store favorites are not correctly cached
Steps to reproduce:

1. Change your favorites
2. Go to any application
3. Click back in your browser

https://images.zenhubusercontent.com/102488820/2a753b8d-5528-4de6-95f1-ead0a05f8331/app_store_favorite_issue.mp4

### PR DESCRIPTION
**Pull request by xiroV**
fixes #2181
fixes #2185

### CODE REVIEW

File: frontend-web/webclient/app/Applications/Overview.tsx [hunk 1]
```diff
@@ -170,16 +175,16 @@ interface TagGridProps {
...
 
 const TagGrid: React.FunctionComponent<TagGridProps> = (
-    {tag, columns, rows, tagBanList = [], favoriteStatus, onFavorite, linkToRun}: TagGridProps
+    {tag, columns, rows, tagBanList = [], favoriteStatus, onFavorite, linkToRun, refreshId}: TagGridProps
 ) => {
     const showFavorites = tag == SPECIAL_FAVORITE_TAG;
     const [appResp, fetchApplications] = useCloudAPI<UCloud.Page<ApplicationSummaryWithFavorite>>(
         {noop: true},
         emptyPage,
-        {cacheKey: "TagGrid" + tag, cacheTtlMs: TEN_MINUTES_IN_MILLIS}
```
Comment (Tiggles) [inline frontend-web/webclient/app/Applications/Overview.tsx:182]: Removing this line stops caching from working, forcing a full reload on every Apps page access.

**Review by DanThrane — APPROVED** [review]
