### PR TITLE
Accounting problems fixes

### LINKED ISSUE #4127: [dev-2024] Accounting error while creating licenses (and others?)
Steps to reproduce:

1. Create a sub-project (S1) and assign it 2 licenses
2. Activate a single license in S1
3. Sub-allocate 100 licenses to another project (S2)
4. Activate 5 licenses in S2

It should not be possible to combined activate more than 2 licenses, but the system allows you to use up to 100.

### LINKED ISSUE #4128: [dev-2024] Accounting error while running jobs
Steps to reproduce:

- Create a sub-project (S1) and assign it 1 core-hour
- Sub-allocate 100 core-hours to another project (S2)
- Run a job in S2 for several core-hours

### LINKED ISSUE #4129: [dev-2024] It is possible to start a job with 0 compute resources available
Steps to reproduce:

1. Create an allocation
2. Manually update the database to set the balance to 0. Restart the core.
3. Start a job in this project

The job will be terminated after a few minutes, but it should be rejected during the create call in the IM (not by the core!).

### LINKED ISSUE #4130: [dev-2024] TotalCharges will reduce treeusage on parent update even if subalocations still is overusing
Should only change the parent if the usage of the current allocation is going beneath its quota

### PR DESCRIPTION
**Pull request by hschu12**
fixes multiple issues. Fix #4130, made functiont only charge parent tree when current alloc is using less than quota of parent. Fix #4129 Made call to check from IM. Fix #4128 and fix #4127 removed isLocked and replaced by internal function to check parents as well

### CODE REVIEW

File: backend/accounting-service/src/main/kotlin/services/wallets/AccountingProcessor.kt [hunk 1]
```diff
@@ -1525,17 +1565,34 @@ class AccountingProcessor(
...
+                    //Dont update since the usage is still be over consumed so parent should just have quota as treeusage
+                } else {
+                    val previousOvercharge = ((allocation.treeUsage ?: allocation.localUsage) - toCharge) -  allocation.quota
+                    if (previousOvercharge > 0) {
+                        toCharge += previousOvercharge
+                    }
+                    parent.treeUsage = (parent.treeUsage ?: parent.localUsage) + toCharge
+                }
+            } else {
+                println("positive: to char $toCharge")
```
Comment (Tiggles) [inline backend/accounting-service/src/main/kotlin/services/wallets/AccountingProcessor.kt:1588]: Remove

**Review by DanThrane — APPROVED** [review]
