### PR TITLE
Fixes to new app store

### LINKED ISSUE #4068: [ui-redesign] Fixes to App Store
There has been a few bugs and suggested improvements to the new app store.

- [x] Move search field above favorites. Maybe in-line with the context-switcher.
- [x] Redesign favorites-circles. Introduce favorite section on landing page. Reuse existing tall cards.
- [x] "New version available" bubble shows even if there's only version (bug?)
- [x] Remove version as an attribute on favorites
- [x] Remove version as an attribute for default application (in application group).
- [x] Move floating button to bottom
- [x] Top-10 apps section.
- [x] Landing page headline should not be hard-coded.
- [x] Tilt chevron on view all-button.
- [x] Update search bar on both landing and overview pages.
- [x] Fix tag editor
- [x] Re-introduce favorites on app cards
- [x] Fix application page (in Application Studio)

### PR DESCRIPTION
**Pull request by xiroV**
fixes #4068

### CODE REVIEW

File: frontend-web/webclient/app/Applications/ApplicationsRow.tsx [hunk 1]
```diff
@@ -92,74 +130,35 @@ const ApplicationRow: React.FunctionComponent<ApplicationRowProps> = ({
...
-                                    />
-                                </Link>
-                            )}
-                        </Flex>
-                    </div>
-            }
+            <div
+                ref={scrollRef}
+                className={ApplicationRowContainerClass}
+                data-space-between={style === AppCardStyle.WIDE ? (items.length > 3) : (items.length > 6)}
```
Comment (Tiggles) [inline frontend-web/webclient/app/Applications/ApplicationsRow.tsx:136]: `style` is overloaded for me. Calling it `cardStyle` would be better, so it doesn't seem like the `style` is an object of CSSProperties.

File: frontend-web/webclient/app/Applications/ApplicationsRow.tsx [hunk 2]
```diff
@@ -1,34 +1,72 @@
...
+}
+
+export function ApplicationSummaryToRowItem(app: ApplicationSummaryWithFavorite, onFavorite?: (app: ApplicationSummaryWithFavorite) => void): ApplicationRowItem {
+    return {
+        id: app.metadata.name,
+        type: AppCardType.APPLICATION,
+        title: app.metadata.title,
+        description: app.metadata.description,
+        isFavorite: app.favorite,
+        onFavorite: onFavorite,
```
Comment (Tiggles) [inline frontend-web/webclient/app/Applications/ApplicationsRow.tsx:56]: Why is the function saved in the object and not just passed to the same component?

File: frontend-web/webclient/app/Applications/ApplicationsRow.tsx [hunk 3]
```diff
@@ -92,74 +130,35 @@ const ApplicationRow: React.FunctionComponent<ApplicationRowProps> = ({
...
+                        application={item.application}
+                        link={
+                            item.type === AppCardType.APPLICATION ?
+                                Pages.run(item.id)
+                            :
+                                (item.defaultApplication ?
+                                    Pages.run(item.defaultApplication)
+                                :
+                                    Pages.browseGroup(item.id)
+                                )
```
Comment (Tiggles) [inline frontend-web/webclient/app/Applications/ApplicationsRow.tsx:157]: I'd rather that nested terniary checks are moved to a function call.

File: frontend-web/webclient/app/Applications/Group.tsx [hunk 4]
```diff
@@ -24,49 +29,73 @@ const ApplicationsGroup: React.FunctionComponent = () => {
...
+    </Box>;
+}
+
+export default ApplicationsGroup;
+
+function dispatch(arg0: any) {
+    throw new Error("Function not implemented.");
+}
+function invokeCommand(arg0: any) {
+    throw new Error("Function not implemented.");
```
Comment (Tiggles) [inline frontend-web/webclient/app/Applications/Group.tsx:99]: I think you missclicked something when trying to import these

File: frontend-web/webclient/app/Applications/Landing.tsx [hunk 5]
```diff
@@ -19,123 +19,131 @@ import {toggleAppFavorite} from "./Redux/Actions";
...
+            <Icon name="search" size={20} color="darkGray" my="auto" onClick={e => {
+                const queryCurrent = inputRef.current;
+                if (!queryCurrent) return;
+
+                const queryValue = queryCurrent.value;
+
+                if (queryValue === "") return;
+
+                navigate(AppRoutes.apps.search(queryValue));
+            }} />
```
Comment (Tiggles) [inline frontend-web/webclient/app/Applications/Landing.tsx:91]: Move to useCallback instead of repeating

File: frontend-web/webclient/app/Applications/Landing.tsx [hunk 6]
```diff
@@ -269,41 +250,67 @@ function filterAppsByFavorite(
...
+                        <Icon cursor="pointer" name="starFilled" color="blue" hoverColor="blue" size="20px" onClick={() => onFavorite(app)} />
+                    </Relative>
+                </Flex>
             )}
-        </Flex>
-    </Flex>
+        </div>
+        */}
+    </>
 }
```
Comment (Tiggles) [inline frontend-web/webclient/app/Applications/Landing.tsx:314]: Remove comments

**Review by Tiggles — COMMENTED** [review]
Some things to fix.

File: frontend-web/webclient/app/Applications/Group.tsx [hunk 7]
```diff
@@ -20,53 +25,69 @@ const ApplicationsGroup: React.FunctionComponent = () => {
...
+
     useEffect(() => {
         fetchAppGroup(retrieveGroup({id: id}));
     }, [id]);
 
-    if (!appGroup.data) return <>Not found</>;
+    const favoriteStatus = useSelector<ReduxObject, ApplicationSummaryWithFavorite[]>(it => it.sidebar.favorites);
+
+    const onFavorite = useCallback(async (app: ApplicationSummaryWithFavorite) => {
+        // Note(Jonas): This used to check commandLoading (from invokeCommand), but this gets stuck at true, so removed for now.
```
Comment (Tiggles) [inline frontend-web/webclient/app/Applications/Group.tsx:38]: I think this comment is outdated now

File: frontend-web/webclient/app/Applications/Landing.tsx [hunk 8]
```diff
@@ -159,92 +157,71 @@ const ApplicationsLanding: React.FunctionComponent = () => {
...
-                            refreshId={refreshId}
-                        />
-
-                        <LargeSearchBox />
 
-                        {sections.data.sections[0] ?
-                            <>
+                        {favorites.length < 1 ? <></> : <>
+                            <Flex className={AppStoreVisualClass}>
+                                {/* <img src={favoritesImage} /> */}
```
Comment (Tiggles) [inline frontend-web/webclient/app/Applications/Landing.tsx:192]: Remove

File: frontend-web/webclient/app/Dashboard/Dashboard.tsx [hunk 9]
```diff
@@ -364,7 +361,6 @@ function DashboardResources({products}: {
         if (compare !== 0) return compare;
 
         compare = a.productType.localeCompare(b.productType);
-        if (compare !== 0) return compare;
```
Comment (Tiggles) [inline frontend-web/webclient/app/Dashboard/Dashboard.tsx:367]: I might be because of the diff-viewer, but if this line is removed, the one above should be as well, I think.

File: frontend-web/webclient/app/Applications/Landing.tsx (hunk 8 above)
Comment (Tiggles) [reply frontend-web/webclient/app/Applications/Landing.tsx:192]: Line 192, specifically

File: frontend-web/webclient/app/Applications/Group.tsx [hunk 10]
```diff
@@ -20,53 +25,67 @@ const ApplicationsGroup: React.FunctionComponent = () => {
         null
     );
 
+    const dispatch = useDispatch();
+    const [, invokeCommand] = useCloudCommand();
```
Comment (Tiggles) [inline frontend-web/webclient/app/Applications/Group.tsx:29]: If you are not using `loading` from `useCloudCommand`, I think this can be replace with `callAPI`

File: frontend-web/webclient/app/Applications/Group.tsx [hunk 11]
```diff
@@ -20,53 +25,67 @@ const ApplicationsGroup: React.FunctionComponent = () => {
...
-                    <LargeSearchBox />
-                </Absolute>
-            </>
+        try {
+            await invokeCommand(UCloud.compute.apps.toggleFavorite({
+                appName: app.metadata.name
+            }));
+        } catch (e) {
+            dispatch(toggleAppFavorite(app, !isFavorite));
         }
```
Comment (Tiggles) [inline frontend-web/webclient/app/Applications/Group.tsx:49]: I think running `invokeCommand` without passing a second argument, `invokeCommand` will do the error handling

File: frontend-web/webclient/app/Applications/Search.tsx [hunk 12]
```diff
@@ -1,19 +1,106 @@
...
+                    <Icon name="search" size={20} color="darkGray" my="auto" onClick={e => {
+                        const queryCurrent = inputRef.current;
+                        if (!queryCurrent) return;
+
+                        const queryValue = queryCurrent.value;
+
+                        if (queryValue === "") return;
+
+                        navigate(AppRoutes.apps.search(queryValue));
+                    }} />
```
Comment (Tiggles) [inline frontend-web/webclient/app/Applications/Search.tsx:94]: Duplicated function

**Review by Tiggles — COMMENTED** [review]
One thing needs to be fixed, as it can put favorites in the wrong state on failed calls to the backend

File: frontend-web/webclient/app/Applications/Group.tsx [hunk 13]
```diff
@@ -20,53 +24,66 @@ const ApplicationsGroup: React.FunctionComponent = () => {
...
-                <Absolute top="0px" left="calc(50% - 200px)">
-                    <LargeSearchBox />
-                </Absolute>
-            </>
+        try {
+            await callAPI(UCloud.compute.apps.toggleFavorite({
+                appName: app.metadata.name
+            }));
+        } catch (e) {
+            dispatch(toggleAppFavorite(app, !isFavorite));
```
Comment (Tiggles) [inline frontend-web/webclient/app/Applications/Group.tsx:46]: It should notify the user that something went wrong

File: frontend-web/webclient/app/Applications/Search.tsx [hunk 14]
```diff
@@ -63,38 +148,57 @@ export const SearchResults: React.FunctionComponent = () => {
...
+        const isFavorite = favoriteApp !== undefined ? true : app.favorite;
+
+        dispatch(toggleAppFavorite(app, !isFavorite));
+
+        try {
+            await callAPI(UCloud.compute.apps.toggleFavorite({
+                appName: app.metadata.name
+            }));
+        } catch (e) {
+            dispatch(toggleAppFavorite(app, !isFavorite));
```
Comment (Tiggles) [inline frontend-web/webclient/app/Applications/Search.tsx:164]: It should notify the user that something went wrong

File: frontend-web/webclient/app/Applications/Search.tsx [hunk 15]
```diff
@@ -63,38 +149,58 @@ export const SearchResults: React.FunctionComponent = () => {
...
+        const isFavorite = favoriteApp !== undefined ? true : app.favorite;
+
+        dispatch(toggleAppFavorite(app, !isFavorite));
+
+        try {
+            await callAPI(UCloud.compute.apps.toggleFavorite({
+                appName: app.metadata.name
+            }));
+        } catch (e) {
+            snackbarStore.addFailure("Failed to toggle favorite", false);
```
Comment (Tiggles) [inline frontend-web/webclient/app/Applications/Search.tsx:165]: Either `displayErrorMessageOrDefault(e, "Failed to toggle favorite")` or rewrite to `} catch {`

File: frontend-web/webclient/app/Applications/Group.tsx [hunk 16]
```diff
@@ -20,53 +25,67 @@ const ApplicationsGroup: React.FunctionComponent = () => {
...
-                <Absolute top="0px" left="calc(50% - 200px)">
-                    <LargeSearchBox />
-                </Absolute>
-            </>
+        try {
+            await callAPI(UCloud.compute.apps.toggleFavorite({
+                appName: app.metadata.name
+            }));
+        } catch (e) {
+            snackbarStore.addFailure("Failed to toggle favorite", false);
```
Comment (Tiggles) [inline frontend-web/webclient/app/Applications/Group.tsx:47]: Either `displayErrorMessageOrDefault(e, "Failed to toggle favorite")` or rewrite to `} catch {`

**Review by Tiggles — APPROVED** [review]

**Review by DanThrane — APPROVED** [review]
