### PR TITLE
Grant Transfer update

### LINKED ISSUE #4279: Grant transfer does not work

### PR DESCRIPTION
**Pull request by hschu12**
Fixed #4279 . Also made comment section auto scroll down to newest revision or comment.

Only shows transfer options based on grant seekers available grant givers (not included those already in the grant).
Might be a better way for the frontend to show the possible transfer options than the new element "possibleTransfers" identical to "allcoators", but the "allocators" element was filtered and modified to only contain the allocators that was requested for resources in the grant, so it did not contain all possible grant givers of the grant seeker.

Not sure if it should be possible to transfer to a grant giver that is already participating in the grant. If it should be possible should the resources that overlap then just be summed or should something else happen?

### CODE REVIEW

File: frontend-web/webclient/app/Grants/Editor.tsx [hunk 1]
```diff
@@ -2331,7 +2342,7 @@ const GrantGiver: React.FunctionComponent<{
         if (!props.onTransfer) return;
 
         const result = await transferProject(
-            props.allAllocators.filter(it => !it.checked && it.id !== props.projectId)
+            props.transfers.filter(it => !it.checked && it.id !== props.projectId)
```
Comment (Tiggles) [inline frontend-web/webclient/app/Grants/Editor.tsx:2345]: Am I missing something or are `transfers` and `allAllocations` equal to each other?

Comment (DanThrane) [reply frontend-web/webclient/app/Grants/Editor.tsx:2345]: They look identical to me. I am not sure if that is intended.

**Review by DanThrane — CHANGES_REQUESTED** [review]
Some stylistic changes. Can you clarify your intend with `transfers` and `allAllocations` in the frontend?

File: frontend-web/webclient/app/Grants/Editor.tsx (hunk 1 above)
Comment (Tiggles) [reply frontend-web/webclient/app/Grants/Editor.tsx:2345]: As far as I can see, these can diverge when calling `loadRevision`, so I don't think they are guaranteed to be equal.

Comment (Tiggles) [reply frontend-web/webclient/app/Grants/Editor.tsx:2345]: This is part of the initial comment, so maybe I should have read that first.

**Review by DanThrane — APPROVED** [review]
