### PR TITLE
Metadata fix

### LINKED ISSUE #2717: [storage] File Metadata not updated when file is moved to trash.
Create folder, favorite, de-favorite, move to trash.

Create folder, see that previous metadata operations are attached to folder that now resides in trash.

### LINKED ISSUE #2975: File metadata for shared files does not work

### PR DESCRIPTION
**Pull request by hschu12**
Fixes #2975 and fixes #2717

### CODE REVIEW

File: backend/file-orchestrator-service/src/jvmMain/kotlin/service/MetadataService.kt [hunk 1]
```diff
@@ -261,13 +327,34 @@ class MetadataService(
             val metadata = HashMap<String, HashMap<String, ArrayList<FileMetadataOrDeleted>>>()
             val templates = HashMap<String, FileMetadataTemplate>()
 
+            val id = extractPathMetadata(normalizedParentPath).collection
+            val rows = session.sendPreparedStatement(
+                {
+                    setParameter("collectionPath", "/$id")
+                },
+                """
+                    Select original_file_path
```
Comment (DanThrane) [inline backend/file-orchestrator-service/src/jvmMain/kotlin/service/MetadataService.kt:336]:
```suggestion
                    select original_file_path
```

**Review by DanThrane — CHANGES_REQUESTED** [review]

**Review by DanThrane — DISMISSED** [review]
Looks good to me.

**Review by DanThrane — APPROVED** [review]
