### PR TITLE
Quick Launch fixed with option to select machine

### LINKED ISSUE #2247: Quick launch no longer works
Using the quick launch feature from the frontend no longer appear to work

### PR DESCRIPTION
**Pull request by xiroV**
Fixes the Quick Launch feature (it haven't been working for a while), and adds a pop-up/modal in case the user have credit available for multiple machines, allowing the user to select which machine to use.

In case the user only have access to 1 machine, the machine will be chosen and launched automatically (as before).

fixes #2247

### CODE REVIEW

File: frontend-web/webclient/app/Files/LowLevelFileTable.tsx [hunk 1]
```diff
@@ -398,6 +418,77 @@ export const LowLevelFileTable: React.FunctionComponent<LowLevelFileTableProps>
...
+        }
+
+        if (selectedQuickLaunchApp !== null) {
+            fetchQuickLaunchApp(
+                compute.apps.findByNameAndVersion({
+                    appName: selectedQuickLaunchApp.metadata.name,
+                    appVersion: selectedQuickLaunchApp.metadata.version
+            }));
+        }
+    }, [wallet, selectedQuickLaunchApp]);
```
Comment (Tiggles) [inline frontend-web/webclient/app/Files/LowLevelFileTable.tsx:439]: If they aren't related, I think they should be in different `useEffects`

File: frontend-web/webclient/app/Files/LowLevelFileTable.tsx [hunk 2]
```diff
@@ -398,6 +418,77 @@ export const LowLevelFileTable: React.FunctionComponent<LowLevelFileTableProps>
...
+                                        return it.support.virtualMachine.enabled &&
+                                            (tool.description.supportedProviders ?? [])
+                                                .some(p => p === it.product.category.provider);
+                                }
+                            })
+                            .filter(product =>
+                                wallet.data.items.some(wallet => productCategoryEquals(product.product.category, wallet.category))
+                            )
+                            .map(it => it.product);
+                    })
```
Comment (Tiggles) [inline frontend-web/webclient/app/Files/LowLevelFileTable.tsx:467]: I don't understand the usage of `apply` here. This could be simplified.

File: frontend-web/webclient/app/Files/LowLevelFileTable.tsx [hunk 3]
```diff
@@ -575,6 +666,22 @@ export const LowLevelFileTable: React.FunctionComponent<LowLevelFileTableProps>
                             />
                         </StickyBox>
                     )}
+                    <ReactModal isOpen={selectProduct}
+                        onRequestClose={() => setSelectProduct(false)}
+                        shouldCloseOnEsc
+                        ariaHideApp={false}
```
Comment (Tiggles) [inline frontend-web/webclient/app/Files/LowLevelFileTable.tsx:672]: I think this messes with screen-readers. Adding the other approach mention by the `console.log` instead.

File: frontend-web/webclient/app/Files/LowLevelFileTable.tsx [hunk 4]
```diff
@@ -608,6 +715,28 @@ export const LowLevelFileTable: React.FunctionComponent<LowLevelFileTableProps>
         setCheckedFiles(checked);
     }
 
+    function onQuickLaunch(app: QuickLaunchApp) {
+        fetchWallet(accounting.products.browse({filterUsable: true, filterArea: "COMPUTE", itemsPerPage: 250, includeBalance: true}));
+        setSelectedQuickLaunchApp(app);
+    }
+
+    function quickLaunchOnSelectedMachine() {
+        if(selectedMachine !== null && quickLaunchApp.data !== null && props.path) {
```
Comment (Tiggles) [inline frontend-web/webclient/app/Files/LowLevelFileTable.tsx:724]: Formatting

File: frontend-web/webclient/app/Files/LowLevelFileTable.tsx [hunk 5]
```diff
@@ -768,7 +897,8 @@ export const LowLevelFileTable: React.FunctionComponent<LowLevelFileTableProps>
                                             >
                                                 <QuickLaunchApps
                                                     file={f}
-                                                    applications={applications.get(f.path)}
+                                                    applications={applications.get(f.path)!!}
```
Comment (Tiggles) [inline frontend-web/webclient/app/Files/LowLevelFileTable.tsx:900]: One bang is enough.

**Review by Tiggles — CHANGES_REQUESTED** [review]
Some changes needed.

File: frontend-web/webclient/app/Files/LowLevelFileTable.tsx (hunk 2 above)
Comment (xiroV) [reply frontend-web/webclient/app/Files/LowLevelFileTable.tsx]: We are essentially concatenating a list (providers) of lists (providers' products) into a list of products. I've removed the `concat.apply`. It works almost the same way now, but I would say that this is much more readable. If you have a better way to do this, please let me know.

File: frontend-web/webclient/app/Files/LowLevelFileTable.tsx (hunk 3 above)
Comment (Tiggles) [reply frontend-web/webclient/app/Files/LowLevelFileTable.tsx:671]: You haven't removed this line?

File: frontend-web/webclient/app/Files/LowLevelFileTable.tsx [hunk 6]
```diff
@@ -608,6 +714,28 @@ export const LowLevelFileTable: React.FunctionComponent<LowLevelFileTableProps>
...
+                    provider: selectedMachine.category.provider
+                },
+                props.path,
+                history
+            )
+        } else {
+            snackbarStore.addFailure("Please select a machine type", true)
+        }
+    }
+
```
Comment (Tiggles) [inline frontend-web/webclient/app/Files/LowLevelFileTable.tsx:738]: `useCallback` could be used here. Not a necessity.

**Review by Tiggles — CHANGES_REQUESTED** [review]
One thing needs to change before I can approve it.

File: frontend-web/webclient/app/Files/LowLevelFileTable.tsx [hunk 7]
```diff
@@ -398,6 +420,100 @@ export const LowLevelFileTable: React.FunctionComponent<LowLevelFileTableProps>
...
+                    category: selectedMachine.category.id,
+                    provider: selectedMachine.category.provider
+                },
+                props.path,
+                history
+            )
+        } else {
+            snackbarStore.addFailure("Please select a machine type", true)
+        }
+    }, [selectedMachine, quickLaunchApp, props.path]);
```
Comment (Tiggles) [inline frontend-web/webclient/app/Files/LowLevelFileTable.tsx:515]: Have you tested these, make sure the closures update correctly?

Comment (xiroV) [reply frontend-web/webclient/app/Files/LowLevelFileTable.tsx:515]: I have double checked now, they all seem to update properly.

**Review by Tiggles — APPROVED** [review]
